FROM python:3.11.6-alpine3.18

RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev cargo

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

WORKDIR /app/healthcare-template-app/

RUN rm -f /app/healthcare-template-app/instance/app.db

##### FOR DOCKER CONTAINER DEV ENV WITH MYSQL #####
EXPOSE 5005
COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
