version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'appdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: 
      context: .
      dockerfile: Dockerfile.Dev.MySQL
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://user:password@db/appdb
    depends_on:
      - db
    restart: always

volumes:
  mysql-data:
