# Environment
ENVIRONMENT: STAGING

# Request Protocols 
PREFERRED_URL_SCHEME: https
BASE_URL: https://localhost:5005

# Sessions/Cookies
PERMANENT_SESSION_LIFETIME: 15  # number in minutes; this is how long the session will last
REMEMBER_COOKIE_DURATION: 7 # number of DAYS to remember the user

# Password restrictions
PASSWORD_MIN_LENGTH: 8
PASSWORD_REQ_UPPERCASE: True
PASSWORD_REQ_LOWERCASE: True
PASSWORD_REQ_DIGIT: True
PASSWORD_REQ_SPECIAL: True

# API Tokens
TOKEN_EXPIRATION_DAYS: 7 # days untill the token will expire

# 2FA Required 
TWO_FACTOR_AUTH_REQUIRED: False

